/* Autogenerated by build.rs. Do not edit. */

pub const IDI_ICON_APP: usize = 1001;
pub const IDI_ICON_GAME_LOCK_ON: usize = 1002;
pub const IDI_ICON_GAME_LOCK_OFF: usize = 1003;
pub const IDS_APP_TITLE: usize = 1001;
pub const IDS_CLEAR_LOG: usize = 1002;
pub const IDS_ENABLED: usize = 1003;
pub const IDS_EXIT: usize = 1004;
pub const IDS_FILE: usize = 1005;
pub const IDS_PROFILE_LOADED: usize = 1006;
pub const IDS_LOG: usize = 1007;
pub const IDS_LOGGING_ENABLED: usize = 1008;
pub const IDS_OPEN: usize = 1009;
pub const IDS_PROFILE: usize = 1010;
pub const IDS_TRAY_TIP: usize = 1012;
pub const IDS__LOGGING_DISABLED_: usize = 1013;
pub const IDS__LOGGING_ENABLED_: usize = 1014;
pub const IDS__PROCESSING_DISABLED_: usize = 1015;
pub const IDS__PROCESSING_ENABLED_: usize = 1016;
pub const IDS_AUTO_SWITCH_PROFILE: usize = 1017;
