/* Autogenerated by build.rs. Do not edit. */

pub(crate) const IDI_ICON_APP: usize = 1001;
pub(crate) const IDI_ICON_GAME_LOCK_ON: usize = 1002;
pub(crate) const IDI_ICON_GAME_LOCK_OFF: usize = 1003;
pub(crate) const IDS_APP_TITLE: usize = 1001;
pub(crate) const IDS_CLEAR_LOG: usize = 1002;
pub(crate) const IDS_ENABLED: usize = 1003;
pub(crate) const IDS_EXIT: usize = 1004;
pub(crate) const IDS_FILE: usize = 1005;
pub(crate) const IDS_LOG: usize = 1007;
pub(crate) const IDS_LOGGING_ENABLED: usize = 1008;
pub(crate) const IDS_OPEN: usize = 1009;
pub(crate) const IDS_LAYOUT: usize = 1010;
pub(crate) const IDS_NO_LAYOUT: usize = 1011;
pub(crate) const IDS_TRAY_TIP: usize = 1012;
pub(crate) const IDS_ACTION: usize = 1013;
pub(crate) const IDS_RULE: usize = 1014;
pub(crate) const IDS_MODIFIERS: usize = 1015;
pub(crate) const IDS_TRANSITION: usize = 1016;
pub(crate) const IDS_AUTO_SWITCH_LAYOUT: usize = 1017;
pub(crate) const IDS_KEY: usize = 1018;
pub(crate) const IDS_STATUS: usize = 1019;
pub(crate) const IDS_TIME: usize = 1020;
pub(crate) const IDS_VIRTUAL_KEY: usize = 1021;
pub(crate) const IDS_SCAN_CODE: usize = 1022;
