/* Autogenerated by build.rs. Do not edit. */

pub(crate) const IDI_ICON_APP: usize = 1001;
pub(crate) const IDI_ICON_GAME_LOCK_ON: usize = 1002;
pub(crate) const IDI_ICON_GAME_LOCK_OFF: usize = 1003;
