app_title = "Keympostor"
tray_tip = "Keympostor"
clear_log = "Clear log"
file = "File"
exit = "Exit"
open = "Open"
profile = "Profile"
log = "Log"
enabled = "Enabled"
logging_enabled = "Logging enabled"
_logging_enabled_ = "--- Logging enabled"
_logging_disabled_ = "--- Logging disabled"