use native_windows_gui::{EmbedResource, Icon};

pub(crate) mod res_ids; /* autogenerated */

#[macro_export]
macro_rules! rs {
    ($res_id:ident) => {
        &RESOURCES.with(|r| r.string($res_id))
    };
}

#[macro_export]
macro_rules! r_icon {
    ($res_id:ident) => {
        RESOURCES.with(|r| r.icon($res_id))
    };
}

thread_local! {
    pub(crate) static RESOURCES: Resources = Resources::new();
}

pub(crate) struct Resources {
    embed: EmbedResource,
}

impl Resources {
    fn new() -> Self {
        Self {
            embed: EmbedResource::load(None).expect("Unable to load embedded resources"),
        }
    }

    pub(crate) fn icon(&self, res_id: usize) -> Icon {
        let mut icon = Icon::default();

        Icon::builder()
            .source_embed(Some(&self.embed))
            .source_embed_id(res_id)
            .strict(true)
            .size(Some((16, 16)))
            .build(&mut icon)
            .expect("Unable to load resource icon");

        icon
    }

    pub(crate) fn string(&self, res_id: usize) -> String {
        self.embed
            .string(res_id as u32)
            .expect("Unable to read resource string")
    }
}

#[cfg(test)]
mod test {

    use crate::res::res_ids::IDI_ICON_APP;
    use crate::res::RESOURCES;
    use log::LevelFilter;
    use simple_logger::SimpleLogger;

    // #[test]
    // fn test_rs() {
    //     assert_eq!("Keympostor", rs!(IDS_APP_TITLE));
    // }
    pub fn setup_test_logger() {
        SimpleLogger::new()
            .with_level(LevelFilter::Debug)
            .init()
            .expect("Failed to initialize logger.");
    }

    #[test]
    fn test_r_icon() {
        assert_ne!(std::ptr::null_mut(), r_icon!(IDI_ICON_APP).handle);
    }

}
