pub(crate) const fn virtual_key_as_str(code: u8) -> &'static str {
    VIRTUAL_KEY_NAME[code as usize]
}

// pub(crate) fn virtual_key_from_str(s: &str) -> Option<u8> {
//     VIRTUAL_KEY_NAME
//         .iter()
//         .position(|name| *name == s)
//         .map(|code| code as u8)
// }

static VIRTUAL_KEY_NAME: [&str; 256] = [
    "UNASSIGNED",
    "VK_LBUTTON",
    "VK_RBUTTON",
    "VK_CANCEL",
    "VK_MBUTTON",
    "VK_XBUTTON1",
    "VK_XBUTTON2",
    "UNASSIGNED",
    "VK_BACK",
    "VK_TAB",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_CLEAR",
    "VK_RETURN",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_SHIFT",
    "VK_CONTROL",
    "VK_MENU",
    "VK_PAUSE",
    "VK_CAPITAL",
    "VK_KANA",
    "VK_IME_ON",
    "VK_JUNJA",
    "VK_FINAL",
    "VK_HANJA",
    "VK_IME_OFF",
    "VK_ESCAPE",
    "VK_CONVERT",
    "VK_NONCONVERT",
    "VK_ACCEPT",
    "VK_MODECHANGE",
    "VK_SPACE",
    "VK_PRIOR",
    "VK_NEXT",
    "VK_END",
    "VK_HOME",
    "VK_LEFT",
    "VK_UP",
    "VK_RIGHT",
    "VK_DOWN",
    "VK_SELECT",
    "VK_PRINT",
    "VK_EXECUTE",
    "VK_SNAPSHOT",
    "VK_INSERT",
    "VK_DELETE",
    "VK_HELP",
    "VK_0",
    "VK_1",
    "VK_2",
    "VK_3",
    "VK_4",
    "VK_5",
    "VK_6",
    "VK_7",
    "VK_8",
    "VK_9",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_A",
    "VK_B",
    "VK_C",
    "VK_D",
    "VK_E",
    "VK_F",
    "VK_G",
    "VK_H",
    "VK_I",
    "VK_J",
    "VK_K",
    "VK_L",
    "VK_M",
    "VK_N",
    "VK_O",
    "VK_P",
    "VK_Q",
    "VK_R",
    "VK_S",
    "VK_T",
    "VK_U",
    "VK_V",
    "VK_W",
    "VK_X",
    "VK_Y",
    "VK_Z",
    "VK_LWIN",
    "VK_RWIN",
    "VK_APPS",
    "UNASSIGNED",
    "VK_SLEEP",
    "VK_NUMPAD0",
    "VK_NUMPAD1",
    "VK_NUMPAD2",
    "VK_NUMPAD3",
    "VK_NUMPAD4",
    "VK_NUMPAD5",
    "VK_NUMPAD6",
    "VK_NUMPAD7",
    "VK_NUMPAD8",
    "VK_NUMPAD9",
    "VK_MULTIPLY",
    "VK_ADD",
    "VK_SEPARATOR",
    "VK_SUBTRACT",
    "VK_DECIMAL",
    "VK_DIVIDE",
    "VK_F1",
    "VK_F2",
    "VK_F3",
    "VK_F4",
    "VK_F5",
    "VK_F6",
    "VK_F7",
    "VK_F8",
    "VK_F9",
    "VK_F10",
    "VK_F11",
    "VK_F12",
    "VK_F13",
    "VK_F14",
    "VK_F15",
    "VK_F16",
    "VK_F17",
    "VK_F18",
    "VK_F19",
    "VK_F20",
    "VK_F21",
    "VK_F22",
    "VK_F23",
    "VK_F24",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_NUMLOCK",
    "VK_SCROLL",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_LSHIFT",
    "VK_RSHIFT",
    "VK_LCONTROL",
    "VK_RCONTROL",
    "VK_LMENU",
    "VK_RMENU",
    "VK_BROWSER_BACK",
    "VK_BROWSER_FORWARD",
    "VK_BROWSER_REFRESH",
    "VK_BROWSER_STOP",
    "VK_BROWSER_SEARCH",
    "VK_BROWSER_FAVORITES",
    "VK_BROWSER_HOME",
    "VK_VOLUME_MUTE",
    "VK_VOLUME_DOWN",
    "VK_VOLUME_UP",
    "VK_MEDIA_NEXT_TRACK",
    "VK_MEDIA_PREV_TRACK",
    "VK_MEDIA_STOP",
    "VK_MEDIA_PLAY_PAUSE",
    "VK_LAUNCH_MAIL",
    "VK_LAUNCH_MEDIA_SELECT",
    "VK_LAUNCH_APP1",
    "VK_LAUNCH_APP2",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_OEM_1",
    "VK_OEM_PLUS",
    "VK_OEM_COMMA",
    "VK_OEM_MINUS",
    "VK_OEM_PERIOD",
    "VK_OEM_2",
    "VK_OEM_3",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_OEM_4",
    "VK_OEM_5",
    "VK_OEM_6",
    "VK_OEM_7",
    "VK_OEM_8",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_OEM_102",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_PROCESSKEY",
    "UNASSIGNED",
    "VK_PACKET",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_ATTN",
    "VK_CRSEL",
    "VK_EXSEL",
    "VK_EREOF",
    "VK_PLAY",
    "VK_ZOOM",
    "VK_NONAME",
    "VK_PA1",
    "VK_OEM_CLEAR",
    "VK__none_",
];

pub(crate) const fn ext_scan_code(code: u8, is_ext: bool) -> u16 {
    if is_ext {
        code as u16 | 0xE0 << 8
    } else {
        code as u16
    }
}

pub(crate) const fn scan_code_as_str(code: u8, is_ext: bool) -> &'static str {
    SCAN_CODE_NAME[code as usize][is_ext as usize]
}

static SCAN_CODE_NAME: [[&str; 2]; 136] = [
    ["UNASSIGNED", "UNASSIGNED"],
    ["SC_ESC", "SC_"],
    ["SC_1", "SC_1"],
    ["SC_2", "SC_2"],
    ["SC_3", "SC_3"],
    ["SC_4", "SC_4"],
    ["SC_5", "SC_5"],
    ["SC_6", "SC_6"],
    ["SC_7", "SC_7"],
    ["SC_8", "SC_8"],
    ["SC_9", "SC_9"],
    ["SC_0", "SC_0"],
    ["SC_MINUS", "SC_MINUS"],
    ["SC_EQ", "SC_EQ"],
    ["SC_BACKSPACE", "SC_BACKSPACE"],
    ["SC_TAB", "SC_TAB"],
    ["SC_Q", "SC_Q"],
    ["SC_W", "SC_W"],
    ["SC_E", "SC_E"],
    ["SC_R", "SC_R"],
    ["SC_T", "SC_T"],
    ["SC_Y", "SC_Y"],
    ["SC_U", "SC_U"],
    ["SC_I", "SC_I"],
    ["SC_O", "SC_O"],
    ["SC_P", "SC_P"],
    ["SC_L_BRACKET", "SC_L_BRACKET"],
    ["SC_R_BRACKET", "SC_R_BRACKET"],
    ["SC_ENTER", "SC_NUM_ENTER"],
    ["SC_CTRL", "SC_RIGHT_CTRL"],
    ["SC_A", "SC_A"],
    ["SC_S", "SC_S"],
    ["SC_D", "SC_VOL_MUTE"],
    ["SC_F", "SC_CALCULATOR"],
    ["SC_G", "SC_G"],
    ["SC_H", "SC_H"],
    ["SC_J", "SC_J"],
    ["SC_K", "SC_K"],
    ["SC_L", "SC_L"],
    ["SC_SEMICOLON", "SC_SEMICOLON"],
    ["SC_APOSTROPHE", "SC_APOSTROPHE"],
    ["SC_BACKTICK", "SC_BACKTICK"],
    ["SC_SHIFT", "UNASSIGNED"],
    ["SC_BACKSLASH", "SC_BRIGHTNESS"],
    ["SC_Z", "SC_Z"],
    ["SC_X", "SC_X"],
    ["SC_C", "SC_VOLUME_DOWN"],
    ["SC_V", "SC_V"],
    ["SC_B", "SC_VOLUME_UP"],
    ["SC_N", "SC_N"],
    ["SC_M", "SC_M"],
    ["SC_COMMA", "SC_COMMA"],
    ["SC_DOT", "SC_DOT"],
    ["SC_SLASH", "SC_NUM_SLASH"],
    ["SC_RIGHT_SHIFT", "SC_RIGHT_SHIFT"],
    ["SC_NUM_MUL", "SC_PRNT_SCRN"],
    ["SC_ALT", "SC_RIGHT_ALT"],
    ["SC_SPACE", "SC__"],
    ["SC_CAPS_LOCK", "UNASSIGNED"],
    ["SC_F1", "UNASSIGNED"],
    ["SC_F2", "UNASSIGNED"],
    ["SC_F3", "UNASSIGNED"],
    ["SC_F4", "UNASSIGNED"],
    ["SC_F5", "UNASSIGNED"],
    ["SC_F6", "UNASSIGNED"],
    ["SC_F7", "UNASSIGNED"],
    ["SC_F8", "UNASSIGNED"],
    ["SC_F9", "UNASSIGNED"],
    ["SC_F10", "UNASSIGNED"],
    ["SC_PAUSE", "SC_NUM_LOCK"],
    ["SC_SCROLL_LOCK", "SC_BREAK"],
    ["SC_NUM_7", "SC_HOME"],
    ["SC_NUM_8", "SC_UP"],
    ["SC_NUM_9", "SC_PAGE_UP"],
    ["SC_NUM_MINUS", "SC_MINUS"],
    ["SC_NUM_4", "SC_LEFT"],
    ["SC_NUM_5", "UNASSIGNED"],
    ["SC_NUM_6", "SC_RIGHT"],
    ["SC_NUM_PLUS", "SC_PLUS"],
    ["SC_NUM_1", "SC_END"],
    ["SC_NUM_2", "SC_DOWN"],
    ["SC_NUM_3", "SC_PAGE_DOWN"],
    ["SC_NUM_0", "SC_INSERT"],
    ["SC_NUM_DEL", "SC_DELETE"],
    ["SC_SYS_REQ", "SC_<00>"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["SC_BACKSLASH", "SC_HELP"],
    ["SC_F11", "UNASSIGNED"],
    ["SC_F12", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "SC_LEFT_WINDOWS"],
    ["UNASSIGNED", "SC_RIGHT_WINDOWS"],
    ["UNASSIGNED", "SC_APPLICATION"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["SC_F13", "SC_	"],
    ["SC_F14", "UNASSIGNED"],
    ["SC_F15", "UNASSIGNED"],
    ["SC_F16", "UNASSIGNED"],
    ["SC_F17", "UNASSIGNED"],
    ["SC_F18", "UNASSIGNED"],
    ["SC_F19", "UNASSIGNED"],
    ["SC_F20", "UNASSIGNED"],
    ["SC_F21", "UNASSIGNED"],
    ["SC_F22", "UNASSIGNED"],
    ["SC_F23", "UNASSIGNED"],
    ["SC_F24", "UNASSIGNED"],
];

#[cfg(test)]
mod tests {
    use crate::key_code::VIRTUAL_KEY_NAME;

    // #[test]
    fn print_unused() {
        for i in 0..256 {
            if VIRTUAL_KEY_NAME[i] == "UNASSIGNED" {
                println!("VK_{}", i);
            }
        }
    }
}