#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct ScanCode(u8, bool);

impl ScanCode {
    pub fn name(&self) -> &str {
        SCAN_CODE_NAME[self.0 as usize][self.1 as usize]
    }

    pub fn is_ext(&self) -> bool {
        self.1
    }

    pub fn into_ext(self) -> u16 {
        ext_scan_code(self.0, self.1)
    }
}

pub(crate) const fn ext_scan_code(code: u8, is_ext: bool) -> u16 {
    if is_ext {
        code as u16 | 0xE0 << 8
    } else {
        code as u16
    }
}

pub static SCAN_CODE_NAME: [[&str; 2]; 136] = [
    ["UNASSIGNED", "UNASSIGNED"],
    ["SC_ESC", "SC_"],
    ["SC_1", "SC_1"],
    ["SC_2", "SC_2"],
    ["SC_3", "SC_3"],
    ["SC_4", "SC_4"],
    ["SC_5", "SC_5"],
    ["SC_6", "SC_6"],
    ["SC_7", "SC_7"],
    ["SC_8", "SC_8"],
    ["SC_9", "SC_9"],
    ["SC_0", "SC_0"],
    ["SC_MINUS", "SC_MINUS"],
    ["SC_EQ", "SC_EQ"],
    ["SC_BACKSPACE", "SC"],
    ["SC_TAB", "SC_	"],
    ["SC_Q", "SC_Q"],
    ["SC_W", "SC_W"],
    ["SC_E", "SC_E"],
    ["SC_R", "SC_R"],
    ["SC_T", "SC_T"],
    ["SC_Y", "SC_Y"],
    ["SC_U", "SC_U"],
    ["SC_I", "SC_I"],
    ["SC_O", "SC_O"],
    ["SC_P", "SC_P"],
    ["SC_L_BRACKET", "SC_L_BRACKET"],
    ["SC_R_BRACKET", "SC_R_BRACKET"],
    ["SC_ENTER", "SC_NUM_ENTER"],
    ["SC_CTRL", "SC_RIGHT_CTRL"],
    ["SC_A", "SC_A"],
    ["SC_S", "SC_S"],
    ["SC_D", "SC_VOL_MUTE"],
    ["SC_F", "SC_CALCULATOR"],
    ["SC_G", "SC_G"],
    ["SC_H", "SC_H"],
    ["SC_J", "SC_J"],
    ["SC_K", "SC_K"],
    ["SC_L", "SC_L"],
    ["SC_SEMICOLON", "SC_SEMICOLON"],
    ["SC_APOSTROPHE", "SC_APOSTROPHE"],
    ["SC_BACKTICK", "SC_BACKTICK"],
    ["SC_SHIFT", "UNASSIGNED"],
    ["SC_BACKSLASH", "SC_BRIGHTNESS"],
    ["SC_Z", "SC_Z"],
    ["SC_X", "SC_X"],
    ["SC_C", "SC_VOLUME_DOWN"],
    ["SC_V", "SC_V"],
    ["SC_B", "SC_VOLUME_UP"],
    ["SC_N", "SC_N"],
    ["SC_M", "SC_M"],
    ["SC_COMMA", "SC_COMMA"],
    ["SC_DOT", "SC_DOT"],
    ["SC_SLASH", "SC_NUM_SLASH"],
    ["SC_RIGHT_SHIFT", "SC_RIGHT_SHIFT"],
    ["SC_NUM_MUL", "SC_PRNT_SCRN"],
    ["SC_ALT", "SC_RIGHT_ALT"],
    ["SC_SPACE", "SC__"],
    ["SC_CAPS_LOCK", "UNASSIGNED"],
    ["SC_F1", "UNASSIGNED"],
    ["SC_F2", "UNASSIGNED"],
    ["SC_F3", "UNASSIGNED"],
    ["SC_F4", "UNASSIGNED"],
    ["SC_F5", "UNASSIGNED"],
    ["SC_F6", "UNASSIGNED"],
    ["SC_F7", "UNASSIGNED"],
    ["SC_F8", "UNASSIGNED"],
    ["SC_F9", "UNASSIGNED"],
    ["SC_F10", "UNASSIGNED"],
    ["SC_PAUSE", "SC_NUM_LOCK"],
    ["SC_SCROLL_LOCK", "SC_BREAK"],
    ["SC_NUM_7", "SC_HOME"],
    ["SC_NUM_8", "SC_UP"],
    ["SC_NUM_9", "SC_PAGE_UP"],
    ["SC_NUM_MINUS", "SC_MINUS"],
    ["SC_NUM_4", "SC_LEFT"],
    ["SC_NUM_5", "UNASSIGNED"],
    ["SC_NUM_6", "SC_RIGHT"],
    ["SC_NUM_PLUS", "SC_PLUS"],
    ["SC_NUM_1", "SC_END"],
    ["SC_NUM_2", "SC_DOWN"],
    ["SC_NUM_3", "SC_PAGE_DOWN"],
    ["SC_NUM_0", "SC_INSERT"],
    ["SC_NUM_DEL", "SC_DELETE"],
    ["SC_SYS_REQ", "SC_<00>"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["SC_BACKSLASH", "SC_HELP"],
    ["SC_F11", "UNASSIGNED"],
    ["SC_F12", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "SC_LEFT_WINDOWS"],
    ["UNASSIGNED", "SC_RIGHT_WINDOWS"],
    ["UNASSIGNED", "SC_APPLICATION"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["UNASSIGNED", "UNASSIGNED"],
    ["SC_F13", "SC_	"],
    ["SC_F14", "UNASSIGNED"],
    ["SC_F15", "UNASSIGNED"],
    ["SC_F16", "UNASSIGNED"],
    ["SC_F17", "UNASSIGNED"],
    ["SC_F18", "UNASSIGNED"],
    ["SC_F19", "UNASSIGNED"],
    ["SC_F20", "UNASSIGNED"],
    ["SC_F21", "UNASSIGNED"],
    ["SC_F22", "UNASSIGNED"],
    ["SC_F23", "UNASSIGNED"],
    ["SC_F24", "UNASSIGNED"],
];
