use crate::error::KeyError;
use crate::key_error;
use std::str::FromStr;
use windows::Win32::UI::Input::KeyboardAndMouse::VIRTUAL_KEY;

#[repr(transparent)]
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct VirtualKey(pub u8);

impl FromStr for VirtualKey {
    type Err = KeyError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let code = VIRTUAL_KEY_NAME
            .iter()
            .position(|&n| n == s)
            .ok_or(key_error!("Illegal virtual key name: `{}`", s))?;

        Ok(Self(code as u8))
    }
}

impl VirtualKey {
    pub fn name(&self) -> &str {
        VIRTUAL_KEY_NAME[self.0 as usize]
    }
}

impl From<VIRTUAL_KEY> for VirtualKey {
    fn from(value: VIRTUAL_KEY) -> Self {
        Self(value.0 as u8)
    }
}

impl Into<VIRTUAL_KEY> for VirtualKey {
    fn into(self) -> VIRTUAL_KEY {
        VIRTUAL_KEY(self.0 as u16)
    }
}

pub(crate) static VIRTUAL_KEY_NAME: [&str; 256] = [
    "UNASSIGNED",
    "VK_LBUTTON",
    "VK_RBUTTON",
    "VK_CANCEL",
    "VK_MBUTTON",
    "VK_XBUTTON1",
    "VK_XBUTTON2",
    "UNASSIGNED",
    "VK_BACK",
    "VK_TAB",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_CLEAR",
    "VK_RETURN",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_SHIFT",
    "VK_CONTROL",
    "VK_MENU",
    "VK_PAUSE",
    "VK_CAPITAL",
    "VK_KANA",
    "VK_IME_ON",
    "VK_JUNJA",
    "VK_FINAL",
    "VK_HANJA",
    "VK_IME_OFF",
    "VK_ESCAPE",
    "VK_CONVERT",
    "VK_NONCONVERT",
    "VK_ACCEPT",
    "VK_MODECHANGE",
    "VK_SPACE",
    "VK_PRIOR",
    "VK_NEXT",
    "VK_END",
    "VK_HOME",
    "VK_LEFT",
    "VK_UP",
    "VK_RIGHT",
    "VK_DOWN",
    "VK_SELECT",
    "VK_PRINT",
    "VK_EXECUTE",
    "VK_SNAPSHOT",
    "VK_INSERT",
    "VK_DELETE",
    "VK_HELP",
    "VK_0",
    "VK_1",
    "VK_2",
    "VK_3",
    "VK_4",
    "VK_5",
    "VK_6",
    "VK_7",
    "VK_8",
    "VK_9",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_A",
    "VK_B",
    "VK_C",
    "VK_D",
    "VK_E",
    "VK_F",
    "VK_G",
    "VK_H",
    "VK_I",
    "VK_J",
    "VK_K",
    "VK_L",
    "VK_M",
    "VK_N",
    "VK_O",
    "VK_P",
    "VK_Q",
    "VK_R",
    "VK_S",
    "VK_T",
    "VK_U",
    "VK_V",
    "VK_W",
    "VK_X",
    "VK_Y",
    "VK_Z",
    "VK_LWIN",
    "VK_RWIN",
    "VK_APPS",
    "UNASSIGNED",
    "VK_SLEEP",
    "VK_NUMPAD0",
    "VK_NUMPAD1",
    "VK_NUMPAD2",
    "VK_NUMPAD3",
    "VK_NUMPAD4",
    "VK_NUMPAD5",
    "VK_NUMPAD6",
    "VK_NUMPAD7",
    "VK_NUMPAD8",
    "VK_NUMPAD9",
    "VK_MULTIPLY",
    "VK_ADD",
    "VK_SEPARATOR",
    "VK_SUBTRACT",
    "VK_DECIMAL",
    "VK_DIVIDE",
    "VK_F1",
    "VK_F2",
    "VK_F3",
    "VK_F4",
    "VK_F5",
    "VK_F6",
    "VK_F7",
    "VK_F8",
    "VK_F9",
    "VK_F10",
    "VK_F11",
    "VK_F12",
    "VK_F13",
    "VK_F14",
    "VK_F15",
    "VK_F16",
    "VK_F17",
    "VK_F18",
    "VK_F19",
    "VK_F20",
    "VK_F21",
    "VK_F22",
    "VK_F23",
    "VK_F24",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_NUMLOCK",
    "VK_SCROLL",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_LSHIFT",
    "VK_RSHIFT",
    "VK_LCONTROL",
    "VK_RCONTROL",
    "VK_LMENU",
    "VK_RMENU",
    "VK_BROWSER_BACK",
    "VK_BROWSER_FORWARD",
    "VK_BROWSER_REFRESH",
    "VK_BROWSER_STOP",
    "VK_BROWSER_SEARCH",
    "VK_BROWSER_FAVORITES",
    "VK_BROWSER_HOME",
    "VK_VOLUME_MUTE",
    "VK_VOLUME_DOWN",
    "VK_VOLUME_UP",
    "VK_MEDIA_NEXT_TRACK",
    "VK_MEDIA_PREV_TRACK",
    "VK_MEDIA_STOP",
    "VK_MEDIA_PLAY_PAUSE",
    "VK_LAUNCH_MAIL",
    "VK_LAUNCH_MEDIA_SELECT",
    "VK_LAUNCH_APP1",
    "VK_LAUNCH_APP2",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_OEM_1",
    "VK_OEM_PLUS",
    "VK_OEM_COMMA",
    "VK_OEM_MINUS",
    "VK_OEM_PERIOD",
    "VK_OEM_2",
    "VK_OEM_3",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_OEM_4",
    "VK_OEM_5",
    "VK_OEM_6",
    "VK_OEM_7",
    "VK_OEM_8",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_OEM_102",
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_PROCESSKEY",
    "UNASSIGNED",
    "VK_PACKET",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED",
    "UNASSIGNED", /* used as a custom MOUSE_X key */
    "UNASSIGNED", /* used as a custom MOUSE_Y key */
    "UNASSIGNED", /* used as a custom WHEEL key */
    "UNASSIGNED", /* used as a custom WHEEL_TILT key */
    "UNASSIGNED",
    "UNASSIGNED",
    "VK_ATTN",
    "VK_CRSEL",
    "VK_EXSEL",
    "VK_EREOF",
    "VK_PLAY",
    "VK_ZOOM",
    "VK_NONAME",
    "VK_PA1",
    "VK_OEM_CLEAR",
    "VK__none_",
];
