use crate::key::{ScanCode, VirtualKey, SCAN_CODES, VIRTUAL_KEYS};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::fmt::{Debug, Display};
use std::str::FromStr;

struct Key {
    id: usize,
    name: &'static str,
    virtual_key: Option<&'static VirtualKey>,
    scan_code: Option<&'static ScanCode>,
}

impl Key {
    fn get(vk: Option<&VirtualKey>, sc: Option<&ScanCode>) -> &'static Self {
        KEYS.iter()
            .find(|k| k.virtual_key == vk || k.scan_code == sc)
            .expect(&format!("Key not found for `{:?}` or `{:?}` ", vk, sc))
    }
    
    fn by_name(name: &str) -> &'static Self {
        KEYS.iter()
            .find(|k| k.name == name || k.virtual_key == VirtualKey::from_str(name) || k.scan_code == sc)
            .expect(&format!("Key not found for `{:?}` or `{:?}` ", vk, sc))
    }
}

macro_rules! new_key {
    ($id:literal, $name:literal, $vk:expr, $sc:expr) => {
        Key {
            id: $id,
            name: $name,
            virtual_key: $vk,
            scan_code: $sc,
        }
    };
}

pub const MAX_KEY: usize = 376;

static KEYS: [Key; MAX_KEY] = [
    new_key!(0, "UNASSIGNED", Some(&VIRTUAL_KEYS[0]), None),
    new_key!(1, "LBUTTON", Some(&VIRTUAL_KEYS[1]), None),
    new_key!(2, "RBUTTON", Some(&VIRTUAL_KEYS[2]), None),
    new_key!(3, "CANCEL", Some(&VIRTUAL_KEYS[3]), Some(&SCAN_CODES[70][1])),
    new_key!(4, "MBUTTON", Some(&VIRTUAL_KEYS[4]), None),
    new_key!(5, "XBUTTON1", Some(&VIRTUAL_KEYS[5]), None),
    new_key!(6, "XBUTTON2", Some(&VIRTUAL_KEYS[6]), None),
    new_key!(7, "UNASSIGNED", Some(&VIRTUAL_KEYS[7]), None),
    new_key!(8, "BACK", Some(&VIRTUAL_KEYS[8]), Some(&SCAN_CODES[14][0])),
    new_key!(9, "TAB", Some(&VIRTUAL_KEYS[9]), Some(&SCAN_CODES[15][0])),
    new_key!(10, "UNASSIGNED", Some(&VIRTUAL_KEYS[10]), None),
    new_key!(11, "UNASSIGNED", Some(&VIRTUAL_KEYS[11]), None),
    new_key!(12, "CLEAR", Some(&VIRTUAL_KEYS[12]), Some(&SCAN_CODES[76][0])),
    new_key!(13, "RETURN", Some(&VIRTUAL_KEYS[13]), Some(&SCAN_CODES[28][0])),
    new_key!(14, "UNASSIGNED", Some(&VIRTUAL_KEYS[14]), None),
    new_key!(15, "UNASSIGNED", Some(&VIRTUAL_KEYS[15]), None),
    new_key!(16, "SHIFT", Some(&VIRTUAL_KEYS[16]), Some(&SCAN_CODES[42][0])),
    new_key!(17, "CONTROL", Some(&VIRTUAL_KEYS[17]), Some(&SCAN_CODES[29][0])),
    new_key!(18, "MENU", Some(&VIRTUAL_KEYS[18]), Some(&SCAN_CODES[56][0])),
    new_key!(19, "PAUSE", Some(&VIRTUAL_KEYS[19]), Some(&SCAN_CODES[29][1])),
    new_key!(20, "CAPITAL", Some(&VIRTUAL_KEYS[20]), Some(&SCAN_CODES[58][0])),
    new_key!(21, "KANA", Some(&VIRTUAL_KEYS[21]), None),
    new_key!(22, "IME_ON", Some(&VIRTUAL_KEYS[22]), None),
    new_key!(23, "JUNJA", Some(&VIRTUAL_KEYS[23]), None),
    new_key!(24, "FINAL", Some(&VIRTUAL_KEYS[24]), None),
    new_key!(25, "HANJA", Some(&VIRTUAL_KEYS[25]), None),
    new_key!(26, "IME_OFF", Some(&VIRTUAL_KEYS[26]), None),
    new_key!(27, "ESCAPE", Some(&VIRTUAL_KEYS[27]), Some(&SCAN_CODES[1][0])),
    new_key!(28, "CONVERT", Some(&VIRTUAL_KEYS[28]), None),
    new_key!(29, "NONCONVERT", Some(&VIRTUAL_KEYS[29]), None),
    new_key!(30, "ACCEPT", Some(&VIRTUAL_KEYS[30]), None),
    new_key!(31, "MODECHANGE", Some(&VIRTUAL_KEYS[31]), None),
    new_key!(32, "SPACE", Some(&VIRTUAL_KEYS[32]), Some(&SCAN_CODES[57][0])),
    new_key!(33, "PRIOR", Some(&VIRTUAL_KEYS[33]), Some(&SCAN_CODES[73][0])),
    new_key!(34, "NEXT", Some(&VIRTUAL_KEYS[34]), Some(&SCAN_CODES[81][0])),
    new_key!(35, "END", Some(&VIRTUAL_KEYS[35]), Some(&SCAN_CODES[79][0])),
    new_key!(36, "HOME", Some(&VIRTUAL_KEYS[36]), Some(&SCAN_CODES[71][0])),
    new_key!(37, "LEFT", Some(&VIRTUAL_KEYS[37]), Some(&SCAN_CODES[75][0])),
    new_key!(38, "UP", Some(&VIRTUAL_KEYS[38]), Some(&SCAN_CODES[72][0])),
    new_key!(39, "RIGHT", Some(&VIRTUAL_KEYS[39]), Some(&SCAN_CODES[77][0])),
    new_key!(40, "DOWN", Some(&VIRTUAL_KEYS[40]), Some(&SCAN_CODES[80][0])),
    new_key!(41, "SELECT", Some(&VIRTUAL_KEYS[41]), None),
    new_key!(42, "PRINT", Some(&VIRTUAL_KEYS[42]), None),
    new_key!(43, "EXECUTE", Some(&VIRTUAL_KEYS[43]), None),
    new_key!(44, "SNAPSHOT", Some(&VIRTUAL_KEYS[44]), Some(&SCAN_CODES[84][0])),
    new_key!(45, "INSERT", Some(&VIRTUAL_KEYS[45]), Some(&SCAN_CODES[82][0])),
    new_key!(46, "DELETE", Some(&VIRTUAL_KEYS[46]), Some(&SCAN_CODES[83][0])),
    new_key!(47, "HELP", Some(&VIRTUAL_KEYS[47]), Some(&SCAN_CODES[99][0])),
    new_key!(48, "0", Some(&VIRTUAL_KEYS[48]), Some(&SCAN_CODES[11][0])),
    new_key!(49, "1", Some(&VIRTUAL_KEYS[49]), Some(&SCAN_CODES[2][0])),
    new_key!(50, "2", Some(&VIRTUAL_KEYS[50]), Some(&SCAN_CODES[3][0])),
    new_key!(51, "3", Some(&VIRTUAL_KEYS[51]), Some(&SCAN_CODES[4][0])),
    new_key!(52, "4", Some(&VIRTUAL_KEYS[52]), Some(&SCAN_CODES[5][0])),
    new_key!(53, "5", Some(&VIRTUAL_KEYS[53]), Some(&SCAN_CODES[6][0])),
    new_key!(54, "6", Some(&VIRTUAL_KEYS[54]), Some(&SCAN_CODES[7][0])),
    new_key!(55, "7", Some(&VIRTUAL_KEYS[55]), Some(&SCAN_CODES[8][0])),
    new_key!(56, "8", Some(&VIRTUAL_KEYS[56]), Some(&SCAN_CODES[9][0])),
    new_key!(57, "9", Some(&VIRTUAL_KEYS[57]), Some(&SCAN_CODES[10][0])),
    new_key!(58, "UNASSIGNED", Some(&VIRTUAL_KEYS[58]), None),
    new_key!(59, "UNASSIGNED", Some(&VIRTUAL_KEYS[59]), None),
    new_key!(60, "UNASSIGNED", Some(&VIRTUAL_KEYS[60]), None),
    new_key!(61, "UNASSIGNED", Some(&VIRTUAL_KEYS[61]), None),
    new_key!(62, "UNASSIGNED", Some(&VIRTUAL_KEYS[62]), None),
    new_key!(63, "UNASSIGNED", Some(&VIRTUAL_KEYS[63]), None),
    new_key!(64, "UNASSIGNED", Some(&VIRTUAL_KEYS[64]), None),
    new_key!(65, "A", Some(&VIRTUAL_KEYS[65]), Some(&SCAN_CODES[30][0])),
    new_key!(66, "B", Some(&VIRTUAL_KEYS[66]), Some(&SCAN_CODES[48][0])),
    new_key!(67, "C", Some(&VIRTUAL_KEYS[67]), Some(&SCAN_CODES[46][0])),
    new_key!(68, "D", Some(&VIRTUAL_KEYS[68]), Some(&SCAN_CODES[32][0])),
    new_key!(69, "E", Some(&VIRTUAL_KEYS[69]), Some(&SCAN_CODES[18][0])),
    new_key!(70, "F", Some(&VIRTUAL_KEYS[70]), Some(&SCAN_CODES[33][0])),
    new_key!(71, "G", Some(&VIRTUAL_KEYS[71]), Some(&SCAN_CODES[34][0])),
    new_key!(72, "H", Some(&VIRTUAL_KEYS[72]), Some(&SCAN_CODES[35][0])),
    new_key!(73, "I", Some(&VIRTUAL_KEYS[73]), Some(&SCAN_CODES[23][0])),
    new_key!(74, "J", Some(&VIRTUAL_KEYS[74]), Some(&SCAN_CODES[36][0])),
    new_key!(75, "K", Some(&VIRTUAL_KEYS[75]), Some(&SCAN_CODES[37][0])),
    new_key!(76, "L", Some(&VIRTUAL_KEYS[76]), Some(&SCAN_CODES[38][0])),
    new_key!(77, "M", Some(&VIRTUAL_KEYS[77]), Some(&SCAN_CODES[50][0])),
    new_key!(78, "N", Some(&VIRTUAL_KEYS[78]), Some(&SCAN_CODES[49][0])),
    new_key!(79, "O", Some(&VIRTUAL_KEYS[79]), Some(&SCAN_CODES[24][0])),
    new_key!(80, "P", Some(&VIRTUAL_KEYS[80]), Some(&SCAN_CODES[25][0])),
    new_key!(81, "Q", Some(&VIRTUAL_KEYS[81]), Some(&SCAN_CODES[16][0])),
    new_key!(82, "R", Some(&VIRTUAL_KEYS[82]), Some(&SCAN_CODES[19][0])),
    new_key!(83, "S", Some(&VIRTUAL_KEYS[83]), Some(&SCAN_CODES[31][0])),
    new_key!(84, "T", Some(&VIRTUAL_KEYS[84]), Some(&SCAN_CODES[20][0])),
    new_key!(85, "U", Some(&VIRTUAL_KEYS[85]), Some(&SCAN_CODES[22][0])),
    new_key!(86, "V", Some(&VIRTUAL_KEYS[86]), Some(&SCAN_CODES[47][0])),
    new_key!(87, "W", Some(&VIRTUAL_KEYS[87]), Some(&SCAN_CODES[17][0])),
    new_key!(88, "X", Some(&VIRTUAL_KEYS[88]), Some(&SCAN_CODES[45][0])),
    new_key!(89, "Y", Some(&VIRTUAL_KEYS[89]), Some(&SCAN_CODES[21][0])),
    new_key!(90, "Z", Some(&VIRTUAL_KEYS[90]), Some(&SCAN_CODES[44][0])),
    new_key!(91, "LWIN", Some(&VIRTUAL_KEYS[91]), Some(&SCAN_CODES[91][1])),
    new_key!(92, "RWIN", Some(&VIRTUAL_KEYS[92]), Some(&SCAN_CODES[92][1])),
    new_key!(93, "APPS", Some(&VIRTUAL_KEYS[93]), Some(&SCAN_CODES[93][1])),
    new_key!(94, "UNASSIGNED", Some(&VIRTUAL_KEYS[94]), None),
    new_key!(95, "SLEEP", Some(&VIRTUAL_KEYS[95]), Some(&SCAN_CODES[95][1])),
    new_key!(96, "NUMPAD0", Some(&VIRTUAL_KEYS[96]), Some(&SCAN_CODES[82][0])),
    new_key!(97, "NUMPAD1", Some(&VIRTUAL_KEYS[97]), Some(&SCAN_CODES[79][0])),
    new_key!(98, "NUMPAD2", Some(&VIRTUAL_KEYS[98]), Some(&SCAN_CODES[80][0])),
    new_key!(99, "NUMPAD3", Some(&VIRTUAL_KEYS[99]), Some(&SCAN_CODES[81][0])),
    new_key!(100, "NUMPAD4", Some(&VIRTUAL_KEYS[100]), Some(&SCAN_CODES[75][0])),
    new_key!(101, "NUMPAD5", Some(&VIRTUAL_KEYS[101]), Some(&SCAN_CODES[76][0])),
    new_key!(102, "NUMPAD6", Some(&VIRTUAL_KEYS[102]), Some(&SCAN_CODES[77][0])),
    new_key!(103, "NUMPAD7", Some(&VIRTUAL_KEYS[103]), Some(&SCAN_CODES[71][0])),
    new_key!(104, "NUMPAD8", Some(&VIRTUAL_KEYS[104]), Some(&SCAN_CODES[72][0])),
    new_key!(105, "NUMPAD9", Some(&VIRTUAL_KEYS[105]), Some(&SCAN_CODES[73][0])),
    new_key!(106, "MULTIPLY", Some(&VIRTUAL_KEYS[106]), Some(&SCAN_CODES[55][0])),
    new_key!(107, "ADD", Some(&VIRTUAL_KEYS[107]), Some(&SCAN_CODES[78][0])),
    new_key!(108, "SEPARATOR", Some(&VIRTUAL_KEYS[108]), None),
    new_key!(109, "SUBTRACT", Some(&VIRTUAL_KEYS[109]), Some(&SCAN_CODES[74][0])),
    new_key!(110, "DECIMAL", Some(&VIRTUAL_KEYS[110]), Some(&SCAN_CODES[83][0])),
    new_key!(111, "DIVIDE", Some(&VIRTUAL_KEYS[111]), Some(&SCAN_CODES[53][1])),
    new_key!(112, "F1", Some(&VIRTUAL_KEYS[112]), Some(&SCAN_CODES[59][0])),
    new_key!(113, "F2", Some(&VIRTUAL_KEYS[113]), Some(&SCAN_CODES[60][0])),
    new_key!(114, "F3", Some(&VIRTUAL_KEYS[114]), Some(&SCAN_CODES[61][0])),
    new_key!(115, "F4", Some(&VIRTUAL_KEYS[115]), Some(&SCAN_CODES[62][0])),
    new_key!(116, "F5", Some(&VIRTUAL_KEYS[116]), Some(&SCAN_CODES[63][0])),
    new_key!(117, "F6", Some(&VIRTUAL_KEYS[117]), Some(&SCAN_CODES[64][0])),
    new_key!(118, "F7", Some(&VIRTUAL_KEYS[118]), Some(&SCAN_CODES[65][0])),
    new_key!(119, "F8", Some(&VIRTUAL_KEYS[119]), Some(&SCAN_CODES[66][0])),
    new_key!(120, "F9", Some(&VIRTUAL_KEYS[120]), Some(&SCAN_CODES[67][0])),
    new_key!(121, "F10", Some(&VIRTUAL_KEYS[121]), Some(&SCAN_CODES[68][0])),
    new_key!(122, "F11", Some(&VIRTUAL_KEYS[122]), Some(&SCAN_CODES[87][0])),
    new_key!(123, "F12", Some(&VIRTUAL_KEYS[123]), Some(&SCAN_CODES[88][0])),
    new_key!(124, "F13", Some(&VIRTUAL_KEYS[124]), Some(&SCAN_CODES[100][0])),
    new_key!(125, "F14", Some(&VIRTUAL_KEYS[125]), Some(&SCAN_CODES[101][0])),
    new_key!(126, "F15", Some(&VIRTUAL_KEYS[126]), Some(&SCAN_CODES[102][0])),
    new_key!(127, "F16", Some(&VIRTUAL_KEYS[127]), Some(&SCAN_CODES[103][0])),
    new_key!(128, "F17", Some(&VIRTUAL_KEYS[128]), Some(&SCAN_CODES[104][0])),
    new_key!(129, "F18", Some(&VIRTUAL_KEYS[129]), Some(&SCAN_CODES[105][0])),
    new_key!(130, "F19", Some(&VIRTUAL_KEYS[130]), Some(&SCAN_CODES[106][0])),
    new_key!(131, "F20", Some(&VIRTUAL_KEYS[131]), Some(&SCAN_CODES[107][0])),
    new_key!(132, "F21", Some(&VIRTUAL_KEYS[132]), Some(&SCAN_CODES[108][0])),
    new_key!(133, "F22", Some(&VIRTUAL_KEYS[133]), Some(&SCAN_CODES[109][0])),
    new_key!(134, "F23", Some(&VIRTUAL_KEYS[134]), Some(&SCAN_CODES[110][0])),
    new_key!(135, "F24", Some(&VIRTUAL_KEYS[135]), Some(&SCAN_CODES[118][0])),
    new_key!(136, "UNASSIGNED", Some(&VIRTUAL_KEYS[136]), None),
    new_key!(137, "UNASSIGNED", Some(&VIRTUAL_KEYS[137]), None),
    new_key!(138, "UNASSIGNED", Some(&VIRTUAL_KEYS[138]), None),
    new_key!(139, "UNASSIGNED", Some(&VIRTUAL_KEYS[139]), None),
    new_key!(140, "UNASSIGNED", Some(&VIRTUAL_KEYS[140]), None),
    new_key!(141, "UNASSIGNED", Some(&VIRTUAL_KEYS[141]), None),
    new_key!(142, "UNASSIGNED", Some(&VIRTUAL_KEYS[142]), None),
    new_key!(143, "UNASSIGNED", Some(&VIRTUAL_KEYS[143]), None),
    new_key!(144, "NUMLOCK", Some(&VIRTUAL_KEYS[144]), Some(&SCAN_CODES[69][0])),
    new_key!(145, "SCROLL", Some(&VIRTUAL_KEYS[145]), Some(&SCAN_CODES[70][0])),
    new_key!(146, "UNASSIGNED", Some(&VIRTUAL_KEYS[146]), None),
    new_key!(147, "UNASSIGNED", Some(&VIRTUAL_KEYS[147]), None),
    new_key!(148, "UNASSIGNED", Some(&VIRTUAL_KEYS[148]), None),
    new_key!(149, "UNASSIGNED", Some(&VIRTUAL_KEYS[149]), None),
    new_key!(150, "UNASSIGNED", Some(&VIRTUAL_KEYS[150]), None),
    new_key!(151, "UNASSIGNED", Some(&VIRTUAL_KEYS[151]), None),
    new_key!(152, "UNASSIGNED", Some(&VIRTUAL_KEYS[152]), None),
    new_key!(153, "UNASSIGNED", Some(&VIRTUAL_KEYS[153]), None),
    new_key!(154, "UNASSIGNED", Some(&VIRTUAL_KEYS[154]), None),
    new_key!(155, "UNASSIGNED", Some(&VIRTUAL_KEYS[155]), None),
    new_key!(156, "UNASSIGNED", Some(&VIRTUAL_KEYS[156]), None),
    new_key!(157, "UNASSIGNED", Some(&VIRTUAL_KEYS[157]), None),
    new_key!(158, "UNASSIGNED", Some(&VIRTUAL_KEYS[158]), None),
    new_key!(159, "UNASSIGNED", Some(&VIRTUAL_KEYS[159]), None),
    new_key!(160, "LSHIFT", Some(&VIRTUAL_KEYS[160]), Some(&SCAN_CODES[42][0])),
    new_key!(161, "RSHIFT", Some(&VIRTUAL_KEYS[161]), Some(&SCAN_CODES[54][0])),
    new_key!(162, "LCONTROL", Some(&VIRTUAL_KEYS[162]), Some(&SCAN_CODES[29][0])),
    new_key!(163, "RCONTROL", Some(&VIRTUAL_KEYS[163]), Some(&SCAN_CODES[29][1])),
    new_key!(164, "LMENU", Some(&VIRTUAL_KEYS[164]), Some(&SCAN_CODES[56][0])),
    new_key!(165, "RMENU", Some(&VIRTUAL_KEYS[165]), Some(&SCAN_CODES[56][1])),
    new_key!(166, "BROWSER_BACK", Some(&VIRTUAL_KEYS[166]), Some(&SCAN_CODES[106][1])),
    new_key!(167, "BROWSER_FORWARD", Some(&VIRTUAL_KEYS[167]), Some(&SCAN_CODES[105][1])),
    new_key!(168, "BROWSER_REFRESH", Some(&VIRTUAL_KEYS[168]), Some(&SCAN_CODES[103][1])),
    new_key!(169, "BROWSER_STOP", Some(&VIRTUAL_KEYS[169]), Some(&SCAN_CODES[104][1])),
    new_key!(170, "BROWSER_SEARCH", Some(&VIRTUAL_KEYS[170]), Some(&SCAN_CODES[101][1])),
    new_key!(171, "BROWSER_FAVORITES", Some(&VIRTUAL_KEYS[171]), Some(&SCAN_CODES[102][1])),
    new_key!(172, "BROWSER_HOME", Some(&VIRTUAL_KEYS[172]), Some(&SCAN_CODES[50][1])),
    new_key!(173, "VOLUME_MUTE", Some(&VIRTUAL_KEYS[173]), Some(&SCAN_CODES[32][1])),
    new_key!(174, "VOLUME_DOWN", Some(&VIRTUAL_KEYS[174]), Some(&SCAN_CODES[46][1])),
    new_key!(175, "VOLUME_UP", Some(&VIRTUAL_KEYS[175]), Some(&SCAN_CODES[48][1])),
    new_key!(176, "MEDIA_NEXT_TRACK", Some(&VIRTUAL_KEYS[176]), Some(&SCAN_CODES[25][1])),
    new_key!(177, "MEDIA_PREV_TRACK", Some(&VIRTUAL_KEYS[177]), Some(&SCAN_CODES[16][1])),
    new_key!(178, "MEDIA_STOP", Some(&VIRTUAL_KEYS[178]), Some(&SCAN_CODES[36][1])),
    new_key!(179, "MEDIA_PLAY_PAUSE", Some(&VIRTUAL_KEYS[179]), Some(&SCAN_CODES[34][1])),
    new_key!(180, "LAUNCH_MAIL", Some(&VIRTUAL_KEYS[180]), Some(&SCAN_CODES[108][1])),
    new_key!(181, "LAUNCH_MEDIA_SELECT", Some(&VIRTUAL_KEYS[181]), Some(&SCAN_CODES[109][1])),
    new_key!(182, "LAUNCH_APP1", Some(&VIRTUAL_KEYS[182]), Some(&SCAN_CODES[107][1])),
    new_key!(183, "LAUNCH_APP2", Some(&VIRTUAL_KEYS[183]), Some(&SCAN_CODES[33][1])),
    new_key!(184, "UNASSIGNED", Some(&VIRTUAL_KEYS[184]), None),
    new_key!(185, "UNASSIGNED", Some(&VIRTUAL_KEYS[185]), None),
    new_key!(186, "OEM_1", Some(&VIRTUAL_KEYS[186]), Some(&SCAN_CODES[39][0])),
    new_key!(187, "OEM_PLUS", Some(&VIRTUAL_KEYS[187]), Some(&SCAN_CODES[13][0])),
    new_key!(188, "OEM_COMMA", Some(&VIRTUAL_KEYS[188]), Some(&SCAN_CODES[51][0])),
    new_key!(189, "OEM_MINUS", Some(&VIRTUAL_KEYS[189]), Some(&SCAN_CODES[12][0])),
    new_key!(190, "OEM_PERIOD", Some(&VIRTUAL_KEYS[190]), Some(&SCAN_CODES[52][0])),
    new_key!(191, "OEM_2", Some(&VIRTUAL_KEYS[191]), Some(&SCAN_CODES[53][0])),
    new_key!(192, "OEM_3", Some(&VIRTUAL_KEYS[192]), Some(&SCAN_CODES[41][0])),
    new_key!(193, "UNASSIGNED", Some(&VIRTUAL_KEYS[193]), Some(&SCAN_CODES[115][0])),
    new_key!(194, "UNASSIGNED", Some(&VIRTUAL_KEYS[194]), Some(&SCAN_CODES[126][0])),
    new_key!(195, "UNASSIGNED", Some(&VIRTUAL_KEYS[195]), None),
    new_key!(196, "UNASSIGNED", Some(&VIRTUAL_KEYS[196]), None),
    new_key!(197, "UNASSIGNED", Some(&VIRTUAL_KEYS[197]), None),
    new_key!(198, "UNASSIGNED", Some(&VIRTUAL_KEYS[198]), None),
    new_key!(199, "UNASSIGNED", Some(&VIRTUAL_KEYS[199]), None),
    new_key!(200, "UNASSIGNED", Some(&VIRTUAL_KEYS[200]), None),
    new_key!(201, "UNASSIGNED", Some(&VIRTUAL_KEYS[201]), None),
    new_key!(202, "UNASSIGNED", Some(&VIRTUAL_KEYS[202]), None),
    new_key!(203, "UNASSIGNED", Some(&VIRTUAL_KEYS[203]), None),
    new_key!(204, "UNASSIGNED", Some(&VIRTUAL_KEYS[204]), None),
    new_key!(205, "UNASSIGNED", Some(&VIRTUAL_KEYS[205]), None),
    new_key!(206, "UNASSIGNED", Some(&VIRTUAL_KEYS[206]), None),
    new_key!(207, "UNASSIGNED", Some(&VIRTUAL_KEYS[207]), None),
    new_key!(208, "UNASSIGNED", Some(&VIRTUAL_KEYS[208]), None),
    new_key!(209, "UNASSIGNED", Some(&VIRTUAL_KEYS[209]), None),
    new_key!(210, "UNASSIGNED", Some(&VIRTUAL_KEYS[210]), None),
    new_key!(211, "UNASSIGNED", Some(&VIRTUAL_KEYS[211]), None),
    new_key!(212, "UNASSIGNED", Some(&VIRTUAL_KEYS[212]), None),
    new_key!(213, "UNASSIGNED", Some(&VIRTUAL_KEYS[213]), None),
    new_key!(214, "UNASSIGNED", Some(&VIRTUAL_KEYS[214]), None),
    new_key!(215, "UNASSIGNED", Some(&VIRTUAL_KEYS[215]), None),
    new_key!(216, "UNASSIGNED", Some(&VIRTUAL_KEYS[216]), None),
    new_key!(217, "UNASSIGNED", Some(&VIRTUAL_KEYS[217]), None),
    new_key!(218, "UNASSIGNED", Some(&VIRTUAL_KEYS[218]), None),
    new_key!(219, "OEM_4", Some(&VIRTUAL_KEYS[219]), Some(&SCAN_CODES[26][0])),
    new_key!(220, "OEM_5", Some(&VIRTUAL_KEYS[220]), Some(&SCAN_CODES[43][0])),
    new_key!(221, "OEM_6", Some(&VIRTUAL_KEYS[221]), Some(&SCAN_CODES[27][0])),
    new_key!(222, "OEM_7", Some(&VIRTUAL_KEYS[222]), Some(&SCAN_CODES[40][0])),
    new_key!(223, "OEM_8", Some(&VIRTUAL_KEYS[223]), None),
    new_key!(224, "UNASSIGNED", Some(&VIRTUAL_KEYS[224]), None),
    new_key!(225, "UNASSIGNED", Some(&VIRTUAL_KEYS[225]), None),
    new_key!(226, "OEM_102", Some(&VIRTUAL_KEYS[226]), Some(&SCAN_CODES[86][0])),
    new_key!(227, "UNASSIGNED", Some(&VIRTUAL_KEYS[227]), None),
    new_key!(228, "UNASSIGNED", Some(&VIRTUAL_KEYS[228]), None),
    new_key!(229, "PROCESSKEY", Some(&VIRTUAL_KEYS[229]), None),
    new_key!(230, "UNASSIGNED", Some(&VIRTUAL_KEYS[230]), None),
    new_key!(231, "PACKET", Some(&VIRTUAL_KEYS[231]), None),
    new_key!(232, "UNASSIGNED", Some(&VIRTUAL_KEYS[232]), None),
    new_key!(233, "UNASSIGNED", Some(&VIRTUAL_KEYS[233]), Some(&SCAN_CODES[113][0])),
    new_key!(234, "UNASSIGNED", Some(&VIRTUAL_KEYS[234]), Some(&SCAN_CODES[92][0])),
    new_key!(235, "UNASSIGNED", Some(&VIRTUAL_KEYS[235]), Some(&SCAN_CODES[123][0])),
    new_key!(236, "UNASSIGNED", Some(&VIRTUAL_KEYS[236]), None),
    new_key!(237, "UNASSIGNED", Some(&VIRTUAL_KEYS[237]), Some(&SCAN_CODES[111][0])),
    new_key!(238, "UNASSIGNED", Some(&VIRTUAL_KEYS[238]), Some(&SCAN_CODES[90][0])),
    new_key!(239, "UNASSIGNED", Some(&VIRTUAL_KEYS[239]), None),
    new_key!(240, "UNASSIGNED", Some(&VIRTUAL_KEYS[240]), None),
    new_key!(241, "UNASSIGNED", Some(&VIRTUAL_KEYS[241]), Some(&SCAN_CODES[91][0])),
    new_key!(242, "UNASSIGNED", Some(&VIRTUAL_KEYS[242]), None),
    new_key!(243, "UNASSIGNED", Some(&VIRTUAL_KEYS[243]), Some(&SCAN_CODES[95][0])),
    new_key!(244, "UNASSIGNED", Some(&VIRTUAL_KEYS[244]), None),
    new_key!(245, "UNASSIGNED", Some(&VIRTUAL_KEYS[245]), Some(&SCAN_CODES[94][0])),
    new_key!(246, "ATTN", Some(&VIRTUAL_KEYS[246]), None),
    new_key!(247, "CRSEL", Some(&VIRTUAL_KEYS[247]), None),
    new_key!(248, "EXSEL", Some(&VIRTUAL_KEYS[248]), None),
    new_key!(249, "EREOF", Some(&VIRTUAL_KEYS[249]), Some(&SCAN_CODES[93][0])),
    new_key!(250, "PLAY", Some(&VIRTUAL_KEYS[250]), None),
    new_key!(251, "ZOOM", Some(&VIRTUAL_KEYS[251]), Some(&SCAN_CODES[98][0])),
    new_key!(252, "NONAME", Some(&VIRTUAL_KEYS[252]), None),
    new_key!(253, "PA1", Some(&VIRTUAL_KEYS[253]), None),
    new_key!(254, "OEM_CLEAR", Some(&VIRTUAL_KEYS[254]), None),
    new_key!(255, "_none_", Some(&VIRTUAL_KEYS[255]), None),
    new_key!(256, "UNASSIGNED", None, Some(&SCAN_CODES[0][0])),
    new_key!(257, "UNASSIGNED", None, Some(&SCAN_CODES[85][0])),
    new_key!(258, "UNASSIGNED", None, Some(&SCAN_CODES[96][0])),
    new_key!(259, "UNASSIGNED", None, Some(&SCAN_CODES[97][0])),
    new_key!(260, "UNASSIGNED", None, Some(&SCAN_CODES[112][0])),
    new_key!(261, "UNASSIGNED", None, Some(&SCAN_CODES[114][0])),
    new_key!(262, "UNASSIGNED", None, Some(&SCAN_CODES[116][0])),
    new_key!(263, "UNASSIGNED", None, Some(&SCAN_CODES[117][0])),
    new_key!(264, "UNASSIGNED", None, Some(&SCAN_CODES[119][0])),
    new_key!(265, "UNASSIGNED", None, Some(&SCAN_CODES[120][0])),
    new_key!(266, "UNASSIGNED", None, Some(&SCAN_CODES[121][0])),
    new_key!(267, "UNASSIGNED", None, Some(&SCAN_CODES[122][0])),
    new_key!(268, "F14", None, Some(&SCAN_CODES[125][0])),
    new_key!(269, "F16", None, Some(&SCAN_CODES[127][0])),
    new_key!(270, "F17", None, Some(&SCAN_CODES[128][0])),
    new_key!(271, "F18", None, Some(&SCAN_CODES[129][0])),
    new_key!(272, "F19", None, Some(&SCAN_CODES[130][0])),
    new_key!(273, "F20", None, Some(&SCAN_CODES[131][0])),
    new_key!(274, "F21", None, Some(&SCAN_CODES[132][0])),
    new_key!(275, "F22", None, Some(&SCAN_CODES[133][0])),
    new_key!(276, "F23", None, Some(&SCAN_CODES[134][0])),
    new_key!(277, "F24", None, Some(&SCAN_CODES[135][0])),
    new_key!(278, "UNASSIGNED", None, Some(&SCAN_CODES[0][1])),
    new_key!(279, "", None, Some(&SCAN_CODES[1][1])),
    new_key!(280, "1", None, Some(&SCAN_CODES[2][1])),
    new_key!(281, "2", None, Some(&SCAN_CODES[3][1])),
    new_key!(282, "3", None, Some(&SCAN_CODES[4][1])),
    new_key!(283, "4", None, Some(&SCAN_CODES[5][1])),
    new_key!(284, "5", None, Some(&SCAN_CODES[6][1])),
    new_key!(285, "6", None, Some(&SCAN_CODES[7][1])),
    new_key!(286, "7", None, Some(&SCAN_CODES[8][1])),
    new_key!(287, "8", None, Some(&SCAN_CODES[9][1])),
    new_key!(288, "9", None, Some(&SCAN_CODES[10][1])),
    new_key!(289, "0", None, Some(&SCAN_CODES[11][1])),
    new_key!(290, "MINUS", None, Some(&SCAN_CODES[12][1])),
    new_key!(291, "EQ", None, Some(&SCAN_CODES[13][1])),
    new_key!(292, "SC", None, Some(&SCAN_CODES[14][1])),
    new_key!(293, "	", None, Some(&SCAN_CODES[15][1])),
    new_key!(294, "W", None, Some(&SCAN_CODES[17][1])),
    new_key!(295, "E", None, Some(&SCAN_CODES[18][1])),
    new_key!(296, "R", None, Some(&SCAN_CODES[19][1])),
    new_key!(297, "T", None, Some(&SCAN_CODES[20][1])),
    new_key!(298, "Y", None, Some(&SCAN_CODES[21][1])),
    new_key!(299, "U", None, Some(&SCAN_CODES[22][1])),
    new_key!(300, "I", None, Some(&SCAN_CODES[23][1])),
    new_key!(301, "O", None, Some(&SCAN_CODES[24][1])),
    new_key!(302, "L_BRACKET", None, Some(&SCAN_CODES[26][1])),
    new_key!(303, "R_BRACKET", None, Some(&SCAN_CODES[27][1])),
    new_key!(304, "A", None, Some(&SCAN_CODES[30][1])),
    new_key!(305, "S", None, Some(&SCAN_CODES[31][1])),
    new_key!(306, "H", None, Some(&SCAN_CODES[35][1])),
    new_key!(307, "K", None, Some(&SCAN_CODES[37][1])),
    new_key!(308, "L", None, Some(&SCAN_CODES[38][1])),
    new_key!(309, "SEMICOLON", None, Some(&SCAN_CODES[39][1])),
    new_key!(310, "APOSTROPHE", None, Some(&SCAN_CODES[40][1])),
    new_key!(311, "BACKTICK", None, Some(&SCAN_CODES[41][1])),
    new_key!(312, "UNASSIGNED", None, Some(&SCAN_CODES[42][1])),
    new_key!(313, "BRIGHTNESS", None, Some(&SCAN_CODES[43][1])),
    new_key!(314, "Z", None, Some(&SCAN_CODES[44][1])),
    new_key!(315, "X", None, Some(&SCAN_CODES[45][1])),
    new_key!(316, "V", None, Some(&SCAN_CODES[47][1])),
    new_key!(317, "N", None, Some(&SCAN_CODES[49][1])),
    new_key!(318, "COMMA", None, Some(&SCAN_CODES[51][1])),
    new_key!(319, "DOT", None, Some(&SCAN_CODES[52][1])),
    new_key!(320, "RIGHT_SHIFT", None, Some(&SCAN_CODES[54][1])),
    new_key!(321, "_", None, Some(&SCAN_CODES[57][1])),
    new_key!(322, "UNASSIGNED", None, Some(&SCAN_CODES[58][1])),
    new_key!(323, "UNASSIGNED", None, Some(&SCAN_CODES[59][1])),
    new_key!(324, "UNASSIGNED", None, Some(&SCAN_CODES[60][1])),
    new_key!(325, "UNASSIGNED", None, Some(&SCAN_CODES[61][1])),
    new_key!(326, "UNASSIGNED", None, Some(&SCAN_CODES[62][1])),
    new_key!(327, "UNASSIGNED", None, Some(&SCAN_CODES[63][1])),
    new_key!(328, "UNASSIGNED", None, Some(&SCAN_CODES[64][1])),
    new_key!(329, "UNASSIGNED", None, Some(&SCAN_CODES[65][1])),
    new_key!(330, "UNASSIGNED", None, Some(&SCAN_CODES[66][1])),
    new_key!(331, "UNASSIGNED", None, Some(&SCAN_CODES[67][1])),
    new_key!(332, "UNASSIGNED", None, Some(&SCAN_CODES[68][1])),
    new_key!(333, "NUM_LOCK", None, Some(&SCAN_CODES[69][1])),
    new_key!(334, "MINUS", None, Some(&SCAN_CODES[74][1])),
    new_key!(335, "UNASSIGNED", None, Some(&SCAN_CODES[76][1])),
    new_key!(336, "PLUS", None, Some(&SCAN_CODES[78][1])),
    new_key!(337, "<00>", None, Some(&SCAN_CODES[84][1])),
    new_key!(338, "UNASSIGNED", None, Some(&SCAN_CODES[85][1])),
    new_key!(339, "HELP", None, Some(&SCAN_CODES[86][1])),
    new_key!(340, "UNASSIGNED", None, Some(&SCAN_CODES[87][1])),
    new_key!(341, "UNASSIGNED", None, Some(&SCAN_CODES[88][1])),
    new_key!(342, "UNASSIGNED", None, Some(&SCAN_CODES[89][1])),
    new_key!(343, "UNASSIGNED", None, Some(&SCAN_CODES[90][1])),
    new_key!(344, "UNASSIGNED", None, Some(&SCAN_CODES[94][1])),
    new_key!(345, "UNASSIGNED", None, Some(&SCAN_CODES[96][1])),
    new_key!(346, "UNASSIGNED", None, Some(&SCAN_CODES[97][1])),
    new_key!(347, "UNASSIGNED", None, Some(&SCAN_CODES[98][1])),
    new_key!(348, "UNASSIGNED", None, Some(&SCAN_CODES[99][1])),
    new_key!(349, "UNASSIGNED", None, Some(&SCAN_CODES[100][1])),
    new_key!(350, "UNASSIGNED", None, Some(&SCAN_CODES[110][1])),
    new_key!(351, "UNASSIGNED", None, Some(&SCAN_CODES[111][1])),
    new_key!(352, "UNASSIGNED", None, Some(&SCAN_CODES[112][1])),
    new_key!(353, "UNASSIGNED", None, Some(&SCAN_CODES[113][1])),
    new_key!(354, "UNASSIGNED", None, Some(&SCAN_CODES[114][1])),
    new_key!(355, "UNASSIGNED", None, Some(&SCAN_CODES[115][1])),
    new_key!(356, "UNASSIGNED", None, Some(&SCAN_CODES[116][1])),
    new_key!(357, "UNASSIGNED", None, Some(&SCAN_CODES[117][1])),
    new_key!(358, "UNASSIGNED", None, Some(&SCAN_CODES[118][1])),
    new_key!(359, "UNASSIGNED", None, Some(&SCAN_CODES[119][1])),
    new_key!(360, "UNASSIGNED", None, Some(&SCAN_CODES[120][1])),
    new_key!(361, "UNASSIGNED", None, Some(&SCAN_CODES[121][1])),
    new_key!(362, "UNASSIGNED", None, Some(&SCAN_CODES[122][1])),
    new_key!(363, "UNASSIGNED", None, Some(&SCAN_CODES[123][1])),
    new_key!(364, "	", None, Some(&SCAN_CODES[124][1])),
    new_key!(365, "UNASSIGNED", None, Some(&SCAN_CODES[125][1])),
    new_key!(366, "UNASSIGNED", None, Some(&SCAN_CODES[126][1])),
    new_key!(367, "UNASSIGNED", None, Some(&SCAN_CODES[127][1])),
    new_key!(368, "UNASSIGNED", None, Some(&SCAN_CODES[128][1])),
    new_key!(369, "UNASSIGNED", None, Some(&SCAN_CODES[129][1])),
    new_key!(370, "UNASSIGNED", None, Some(&SCAN_CODES[130][1])),
    new_key!(371, "UNASSIGNED", None, Some(&SCAN_CODES[131][1])),
    new_key!(372, "UNASSIGNED", None, Some(&SCAN_CODES[132][1])),
    new_key!(373, "UNASSIGNED", None, Some(&SCAN_CODES[133][1])),
    new_key!(374, "UNASSIGNED", None, Some(&SCAN_CODES[134][1])),
    new_key!(375, "UNASSIGNED", None, Some(&SCAN_CODES[135][1])),
];

#[cfg(test)]
mod tests {
    use crate::key::{ScanCode, VirtualKey, MAX_SCAN_CODE, MAX_VK_CODE};
    use crate::key_map::Key;

    #[test]
    fn test_vk_keys() {
        for code in 0..MAX_VK_CODE {
            let vk = VirtualKey::from_code(code as u8).ok();
            let key = Key::get(vk, None);
        }
    }

    #[test]
    fn test_sc_keys() {
        for extended in [false, true] {
            for code in 0..MAX_SCAN_CODE {
                let sc = ScanCode::from_code(code as u8, extended).ok();
                let key = Key::get(None, sc);
            }
        }
    }
}
