use crate::key::{Key, ScanCode, VirtualKey};
use std::collections::HashMap;
use std::sync::LazyLock;

pub(crate) static KEYS: LazyLock<Keys> = LazyLock::new(|| Keys::new());

pub(crate) struct Keys {
    name_to_key_map: HashMap<&'static str, Key>,
}

impl Keys {
    fn new() -> Self {
        Self {
            name_to_key_map: HashMap::from(KEY_NAMES),
        }
    }

    pub(crate) fn by_name(&self, name: &str) -> &Key {
        self.name_to_key_map.get(name).expect(&format!("Unsupported key name: {}", name))
    }
}

const MAX_KEYS: usize = 1;
macro_rules! new_key {
    ($name:literal, $vk_code:literal, $scan_code:literal, $is_ext_scan_code:literal) => {
        (
            $name,
            Key {
                vk_code: $vk_code,
                scan_code: $scan_code,
                is_ext_scan_code: $is_ext_scan_code,
            },
        )
    };
}

static KEY_NAMES: [(&'static str, Key); MAX_KEYS] = [
    new_key!("UNASSIGNED", 0, 0, false)
];

macro_rules! new_vk {
    ($code:literal, $name:literal) => {
        VirtualKey {
            value: $code,
            name: $name,
        }
    };
}

pub(crate) const MAX_VK_CODE: usize = 256;
pub(crate) static VIRTUAL_KEYS: [VirtualKey; MAX_VK_CODE] = [
    new_vk!(0x00, "UNASSIGNED"),
    new_vk!(0x01, "VK_LBUTTON"),
    new_vk!(0x02, "VK_RBUTTON"),
    new_vk!(0x03, "VK_CANCEL"),
    new_vk!(0x04, "VK_MBUTTON"),
    new_vk!(0x05, "VK_XBUTTON1"),
    new_vk!(0x06, "VK_XBUTTON2"),
    new_vk!(0x07, "UNASSIGNED"),
    new_vk!(0x08, "VK_BACK"),
    new_vk!(0x09, "VK_TAB"),
    new_vk!(0x0A, "UNASSIGNED"),
    new_vk!(0x0B, "UNASSIGNED"),
    new_vk!(0x0C, "VK_CLEAR"),
    new_vk!(0x0D, "VK_RETURN"),
    new_vk!(0x0E, "UNASSIGNED"),
    new_vk!(0x0F, "UNASSIGNED"),
    new_vk!(0x10, "VK_SHIFT"),
    new_vk!(0x11, "VK_CONTROL"),
    new_vk!(0x12, "VK_MENU"),
    new_vk!(0x13, "VK_PAUSE"),
    new_vk!(0x14, "VK_CAPITAL"),
    new_vk!(0x15, "VK_KANA"),
    new_vk!(0x16, "VK_IME_ON"),
    new_vk!(0x17, "VK_JUNJA"),
    new_vk!(0x18, "VK_FINAL"),
    new_vk!(0x19, "VK_HANJA"),
    new_vk!(0x1A, "VK_IME_OFF"),
    new_vk!(0x1B, "VK_ESCAPE"),
    new_vk!(0x1C, "VK_CONVERT"),
    new_vk!(0x1D, "VK_NONCONVERT"),
    new_vk!(0x1E, "VK_ACCEPT"),
    new_vk!(0x1F, "VK_MODECHANGE"),
    new_vk!(0x20, "VK_SPACE"),
    new_vk!(0x21, "VK_PRIOR"),
    new_vk!(0x22, "VK_NEXT"),
    new_vk!(0x23, "VK_END"),
    new_vk!(0x24, "VK_HOME"),
    new_vk!(0x25, "VK_LEFT"),
    new_vk!(0x26, "VK_UP"),
    new_vk!(0x27, "VK_RIGHT"),
    new_vk!(0x28, "VK_DOWN"),
    new_vk!(0x29, "VK_SELECT"),
    new_vk!(0x2A, "VK_PRINT"),
    new_vk!(0x2B, "VK_EXECUTE"),
    new_vk!(0x2C, "VK_SNAPSHOT"),
    new_vk!(0x2D, "VK_INSERT"),
    new_vk!(0x2E, "VK_DELETE"),
    new_vk!(0x2F, "VK_HELP"),
    new_vk!(0x30, "VK_0"),
    new_vk!(0x31, "VK_1"),
    new_vk!(0x32, "VK_2"),
    new_vk!(0x33, "VK_3"),
    new_vk!(0x34, "VK_4"),
    new_vk!(0x35, "VK_5"),
    new_vk!(0x36, "VK_6"),
    new_vk!(0x37, "VK_7"),
    new_vk!(0x38, "VK_8"),
    new_vk!(0x39, "VK_9"),
    new_vk!(0x3A, "UNASSIGNED"),
    new_vk!(0x3B, "UNASSIGNED"),
    new_vk!(0x3C, "UNASSIGNED"),
    new_vk!(0x3D, "UNASSIGNED"),
    new_vk!(0x3E, "UNASSIGNED"),
    new_vk!(0x3F, "UNASSIGNED"),
    new_vk!(0x40, "UNASSIGNED"),
    new_vk!(0x41, "VK_A"),
    new_vk!(0x42, "VK_B"),
    new_vk!(0x43, "VK_C"),
    new_vk!(0x44, "VK_D"),
    new_vk!(0x45, "VK_E"),
    new_vk!(0x46, "VK_F"),
    new_vk!(0x47, "VK_G"),
    new_vk!(0x48, "VK_H"),
    new_vk!(0x49, "VK_I"),
    new_vk!(0x4A, "VK_J"),
    new_vk!(0x4B, "VK_K"),
    new_vk!(0x4C, "VK_L"),
    new_vk!(0x4D, "VK_M"),
    new_vk!(0x4E, "VK_N"),
    new_vk!(0x4F, "VK_O"),
    new_vk!(0x50, "VK_P"),
    new_vk!(0x51, "VK_Q"),
    new_vk!(0x52, "VK_R"),
    new_vk!(0x53, "VK_S"),
    new_vk!(0x54, "VK_T"),
    new_vk!(0x55, "VK_U"),
    new_vk!(0x56, "VK_V"),
    new_vk!(0x57, "VK_W"),
    new_vk!(0x58, "VK_X"),
    new_vk!(0x59, "VK_Y"),
    new_vk!(0x5A, "VK_Z"),
    new_vk!(0x5B, "VK_LWIN"),
    new_vk!(0x5C, "VK_RWIN"),
    new_vk!(0x5D, "VK_APPS"),
    new_vk!(0x5E, "UNASSIGNED"),
    new_vk!(0x5F, "VK_SLEEP"),
    new_vk!(0x60, "VK_NUMPAD0"),
    new_vk!(0x61, "VK_NUMPAD1"),
    new_vk!(0x62, "VK_NUMPAD2"),
    new_vk!(0x63, "VK_NUMPAD3"),
    new_vk!(0x64, "VK_NUMPAD4"),
    new_vk!(0x65, "VK_NUMPAD5"),
    new_vk!(0x66, "VK_NUMPAD6"),
    new_vk!(0x67, "VK_NUMPAD7"),
    new_vk!(0x68, "VK_NUMPAD8"),
    new_vk!(0x69, "VK_NUMPAD9"),
    new_vk!(0x6A, "VK_MULTIPLY"),
    new_vk!(0x6B, "VK_ADD"),
    new_vk!(0x6C, "VK_SEPARATOR"),
    new_vk!(0x6D, "VK_SUBTRACT"),
    new_vk!(0x6E, "VK_DECIMAL"),
    new_vk!(0x6F, "VK_DIVIDE"),
    new_vk!(0x70, "VK_F1"),
    new_vk!(0x71, "VK_F2"),
    new_vk!(0x72, "VK_F3"),
    new_vk!(0x73, "VK_F4"),
    new_vk!(0x74, "VK_F5"),
    new_vk!(0x75, "VK_F6"),
    new_vk!(0x76, "VK_F7"),
    new_vk!(0x77, "VK_F8"),
    new_vk!(0x78, "VK_F9"),
    new_vk!(0x79, "VK_F10"),
    new_vk!(0x7A, "VK_F11"),
    new_vk!(0x7B, "VK_F12"),
    new_vk!(0x7C, "VK_F13"),
    new_vk!(0x7D, "VK_F14"),
    new_vk!(0x7E, "VK_F15"),
    new_vk!(0x7F, "VK_F16"),
    new_vk!(0x80, "VK_F17"),
    new_vk!(0x81, "VK_F18"),
    new_vk!(0x82, "VK_F19"),
    new_vk!(0x83, "VK_F20"),
    new_vk!(0x84, "VK_F21"),
    new_vk!(0x85, "VK_F22"),
    new_vk!(0x86, "VK_F23"),
    new_vk!(0x87, "VK_F24"),
    new_vk!(0x88, "UNASSIGNED"),
    new_vk!(0x89, "UNASSIGNED"),
    new_vk!(0x8A, "UNASSIGNED"),
    new_vk!(0x8B, "UNASSIGNED"),
    new_vk!(0x8C, "UNASSIGNED"),
    new_vk!(0x8D, "UNASSIGNED"),
    new_vk!(0x8E, "UNASSIGNED"),
    new_vk!(0x8F, "UNASSIGNED"),
    new_vk!(0x90, "VK_NUMLOCK"),
    new_vk!(0x91, "VK_SCROLL"),
    new_vk!(0x92, "UNASSIGNED"),
    new_vk!(0x93, "UNASSIGNED"),
    new_vk!(0x94, "UNASSIGNED"),
    new_vk!(0x95, "UNASSIGNED"),
    new_vk!(0x96, "UNASSIGNED"),
    new_vk!(0x97, "UNASSIGNED"),
    new_vk!(0x98, "UNASSIGNED"),
    new_vk!(0x99, "UNASSIGNED"),
    new_vk!(0x9A, "UNASSIGNED"),
    new_vk!(0x9B, "UNASSIGNED"),
    new_vk!(0x9C, "UNASSIGNED"),
    new_vk!(0x9D, "UNASSIGNED"),
    new_vk!(0x9E, "UNASSIGNED"),
    new_vk!(0x9F, "UNASSIGNED"),
    new_vk!(0xA0, "VK_LSHIFT"),
    new_vk!(0xA1, "VK_RSHIFT"),
    new_vk!(0xA2, "VK_LCONTROL"),
    new_vk!(0xA3, "VK_RCONTROL"),
    new_vk!(0xA4, "VK_LMENU"),
    new_vk!(0xA5, "VK_RMENU"),
    new_vk!(0xA6, "VK_BROWSER_BACK"),
    new_vk!(0xA7, "VK_BROWSER_FORWARD"),
    new_vk!(0xA8, "VK_BROWSER_REFRESH"),
    new_vk!(0xA9, "VK_BROWSER_STOP"),
    new_vk!(0xAA, "VK_BROWSER_SEARCH"),
    new_vk!(0xAB, "VK_BROWSER_FAVORITES"),
    new_vk!(0xAC, "VK_BROWSER_HOME"),
    new_vk!(0xAD, "VK_VOLUME_MUTE"),
    new_vk!(0xAE, "VK_VOLUME_DOWN"),
    new_vk!(0xAF, "VK_VOLUME_UP"),
    new_vk!(0xB0, "VK_MEDIA_NEXT_TRACK"),
    new_vk!(0xB1, "VK_MEDIA_PREV_TRACK"),
    new_vk!(0xB2, "VK_MEDIA_STOP"),
    new_vk!(0xB3, "VK_MEDIA_PLAY_PAUSE"),
    new_vk!(0xB4, "VK_LAUNCH_MAIL"),
    new_vk!(0xB5, "VK_LAUNCH_MEDIA_SELECT"),
    new_vk!(0xB6, "VK_LAUNCH_APP1"),
    new_vk!(0xB7, "VK_LAUNCH_APP2"),
    new_vk!(0xB8, "UNASSIGNED"),
    new_vk!(0xB9, "UNASSIGNED"),
    new_vk!(0xBA, "VK_OEM_1"),
    new_vk!(0xBB, "VK_OEM_PLUS"),
    new_vk!(0xBC, "VK_OEM_COMMA"),
    new_vk!(0xBD, "VK_OEM_MINUS"),
    new_vk!(0xBE, "VK_OEM_PERIOD"),
    new_vk!(0xBF, "VK_OEM_2"),
    new_vk!(0xC0, "VK_OEM_3"),
    new_vk!(0xC1, "UNASSIGNED"),
    new_vk!(0xC2, "UNASSIGNED"),
    new_vk!(0xC3, "UNASSIGNED"),
    new_vk!(0xC4, "UNASSIGNED"),
    new_vk!(0xC5, "UNASSIGNED"),
    new_vk!(0xC6, "UNASSIGNED"),
    new_vk!(0xC7, "UNASSIGNED"),
    new_vk!(0xC8, "UNASSIGNED"),
    new_vk!(0xC9, "UNASSIGNED"),
    new_vk!(0xCA, "UNASSIGNED"),
    new_vk!(0xCB, "UNASSIGNED"),
    new_vk!(0xCC, "UNASSIGNED"),
    new_vk!(0xCD, "UNASSIGNED"),
    new_vk!(0xCE, "UNASSIGNED"),
    new_vk!(0xCF, "UNASSIGNED"),
    new_vk!(0xD0, "UNASSIGNED"),
    new_vk!(0xD1, "UNASSIGNED"),
    new_vk!(0xD2, "UNASSIGNED"),
    new_vk!(0xD3, "UNASSIGNED"),
    new_vk!(0xD4, "UNASSIGNED"),
    new_vk!(0xD5, "UNASSIGNED"),
    new_vk!(0xD6, "UNASSIGNED"),
    new_vk!(0xD7, "UNASSIGNED"),
    new_vk!(0xD8, "UNASSIGNED"),
    new_vk!(0xD9, "UNASSIGNED"),
    new_vk!(0xDA, "UNASSIGNED"),
    new_vk!(0xDB, "VK_OEM_4"),
    new_vk!(0xDC, "VK_OEM_5"),
    new_vk!(0xDD, "VK_OEM_6"),
    new_vk!(0xDE, "VK_OEM_7"),
    new_vk!(0xDF, "VK_OEM_8"),
    new_vk!(0xE0, "UNASSIGNED"),
    new_vk!(0xE1, "UNASSIGNED"),
    new_vk!(0xE2, "VK_OEM_102"),
    new_vk!(0xE3, "UNASSIGNED"),
    new_vk!(0xE4, "UNASSIGNED"),
    new_vk!(0xE5, "VK_PROCESSKEY"),
    new_vk!(0xE6, "UNASSIGNED"),
    new_vk!(0xE7, "VK_PACKET"),
    new_vk!(0xE8, "UNASSIGNED"),
    new_vk!(0xE9, "UNASSIGNED"),
    new_vk!(0xEA, "UNASSIGNED"),
    new_vk!(0xEB, "UNASSIGNED"),
    new_vk!(0xEC, "UNASSIGNED"),
    new_vk!(0xED, "UNASSIGNED"),
    new_vk!(0xEE, "UNASSIGNED"),
    new_vk!(0xEF, "UNASSIGNED"),
    new_vk!(0xF0, "UNASSIGNED"),
    new_vk!(0xF1, "UNASSIGNED"),
    new_vk!(0xF2, "UNASSIGNED"),
    new_vk!(0xF3, "UNASSIGNED"),
    new_vk!(0xF4, "UNASSIGNED"),
    new_vk!(0xF5, "UNASSIGNED"),
    new_vk!(0xF6, "VK_ATTN"),
    new_vk!(0xF7, "VK_CRSEL"),
    new_vk!(0xF8, "VK_EXSEL"),
    new_vk!(0xF9, "VK_EREOF"),
    new_vk!(0xFA, "VK_PLAY"),
    new_vk!(0xFB, "VK_ZOOM"),
    new_vk!(0xFC, "VK_NONAME"),
    new_vk!(0xFD, "VK_PA1"),
    new_vk!(0xFE, "VK_OEM_CLEAR"),
    new_vk!(0xFF, "VK__none_"),
];

macro_rules! new_sc {
    ($code:literal, $name:literal, $ext_name:literal) => {
        [
            ScanCode {
                value: $code,
                is_extended: false,
                name: $name,
            },
            ScanCode {
                value: $code,
                is_extended: true,
                name: $ext_name,
            },
        ]
    };
}

pub const MAX_SCAN_CODE: usize = 136;
pub(crate) static SCAN_CODES: [[ScanCode; 2]; MAX_SCAN_CODE] = [
    new_sc!(0x00, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x01, "SC_ESC", "SC_"),
    new_sc!(0x02, "SC_1", "SC_1"),
    new_sc!(0x03, "SC_2", "SC_2"),
    new_sc!(0x04, "SC_3", "SC_3"),
    new_sc!(0x05, "SC_4", "SC_4"),
    new_sc!(0x06, "SC_5", "SC_5"),
    new_sc!(0x07, "SC_6", "SC_6"),
    new_sc!(0x08, "SC_7", "SC_7"),
    new_sc!(0x09, "SC_8", "SC_8"),
    new_sc!(0x0A, "SC_9", "SC_9"),
    new_sc!(0x0B, "SC_0", "SC_0"),
    new_sc!(0x0C, "SC_MINUS", "SC_MINUS"),
    new_sc!(0x0D, "SC_EQ", "SC_EQ"),
    new_sc!(0x0E, "SC_BACKSPACE", "SC"),
    new_sc!(0x0F, "SC_TAB", "SC_	"),
    new_sc!(0x10, "SC_Q", "SC_Q"),
    new_sc!(0x11, "SC_W", "SC_W"),
    new_sc!(0x12, "SC_E", "SC_E"),
    new_sc!(0x13, "SC_R", "SC_R"),
    new_sc!(0x14, "SC_T", "SC_T"),
    new_sc!(0x15, "SC_Y", "SC_Y"),
    new_sc!(0x16, "SC_U", "SC_U"),
    new_sc!(0x17, "SC_I", "SC_I"),
    new_sc!(0x18, "SC_O", "SC_O"),
    new_sc!(0x19, "SC_P", "SC_P"),
    new_sc!(0x1A, "SC_L_BRACKET", "SC_L_BRACKET"),
    new_sc!(0x1B, "SC_R_BRACKET", "SC_R_BRACKET"),
    new_sc!(0x1C, "SC_ENTER", "SC_NUM_ENTER"),
    new_sc!(0x1D, "SC_CTRL", "SC_RIGHT_CTRL"),
    new_sc!(0x1E, "SC_A", "SC_A"),
    new_sc!(0x1F, "SC_S", "SC_S"),
    new_sc!(0x20, "SC_D", "SC_VOL_MUTE"),
    new_sc!(0x21, "SC_F", "SC_CALCULATOR"),
    new_sc!(0x22, "SC_G", "SC_G"),
    new_sc!(0x23, "SC_H", "SC_H"),
    new_sc!(0x24, "SC_J", "SC_J"),
    new_sc!(0x25, "SC_K", "SC_K"),
    new_sc!(0x26, "SC_L", "SC_L"),
    new_sc!(0x27, "SC_SEMICOLON", "SC_SEMICOLON"),
    new_sc!(0x28, "SC_APOSTROPHE", "SC_APOSTROPHE"),
    new_sc!(0x29, "SC_BACKTICK", "SC_BACKTICK"),
    new_sc!(0x2A, "SC_SHIFT", "UNASSIGNED"),
    new_sc!(0x2B, "SC_BACKSLASH", "SC_BRIGHTNESS"),
    new_sc!(0x2C, "SC_Z", "SC_Z"),
    new_sc!(0x2D, "SC_X", "SC_X"),
    new_sc!(0x2E, "SC_C", "SC_VOLUME_DOWN"),
    new_sc!(0x2F, "SC_V", "SC_V"),
    new_sc!(0x30, "SC_B", "SC_VOLUME_UP"),
    new_sc!(0x31, "SC_N", "SC_N"),
    new_sc!(0x32, "SC_M", "SC_M"),
    new_sc!(0x33, "SC_COMMA", "SC_COMMA"),
    new_sc!(0x34, "SC_DOT", "SC_DOT"),
    new_sc!(0x35, "SC_SLASH", "SC_NUM_SLASH"),
    new_sc!(0x36, "SC_RIGHT_SHIFT", "SC_RIGHT_SHIFT"),
    new_sc!(0x37, "SC_NUM_MUL", "SC_PRNT_SCRN"),
    new_sc!(0x38, "SC_ALT", "SC_RIGHT_ALT"),
    new_sc!(0x39, "SC_SPACE", "SC__"),
    new_sc!(0x3A, "SC_CAPS_LOCK", "UNASSIGNED"),
    new_sc!(0x3B, "SC_F1", "UNASSIGNED"),
    new_sc!(0x3C, "SC_F2", "UNASSIGNED"),
    new_sc!(0x3D, "SC_F3", "UNASSIGNED"),
    new_sc!(0x3E, "SC_F4", "UNASSIGNED"),
    new_sc!(0x3F, "SC_F5", "UNASSIGNED"),
    new_sc!(0x40, "SC_F6", "UNASSIGNED"),
    new_sc!(0x41, "SC_F7", "UNASSIGNED"),
    new_sc!(0x42, "SC_F8", "UNASSIGNED"),
    new_sc!(0x43, "SC_F9", "UNASSIGNED"),
    new_sc!(0x44, "SC_F10", "UNASSIGNED"),
    new_sc!(0x45, "SC_PAUSE", "SC_NUM_LOCK"),
    new_sc!(0x46, "SC_SCROLL_LOCK", "SC_BREAK"),
    new_sc!(0x47, "SC_NUM_7", "SC_HOME"),
    new_sc!(0x48, "SC_NUM_8", "SC_UP"),
    new_sc!(0x49, "SC_NUM_9", "SC_PAGE_UP"),
    new_sc!(0x4A, "SC_NUM_MINUS", "SC_MINUS"),
    new_sc!(0x4B, "SC_NUM_4", "SC_LEFT"),
    new_sc!(0x4C, "SC_NUM_5", "UNASSIGNED"),
    new_sc!(0x4D, "SC_NUM_6", "SC_RIGHT"),
    new_sc!(0x4E, "SC_NUM_PLUS", "SC_PLUS"),
    new_sc!(0x4F, "SC_NUM_1", "SC_END"),
    new_sc!(0x50, "SC_NUM_2", "SC_DOWN"),
    new_sc!(0x51, "SC_NUM_3", "SC_PAGE_DOWN"),
    new_sc!(0x52, "SC_NUM_0", "SC_INSERT"),
    new_sc!(0x53, "SC_NUM_DEL", "SC_DELETE"),
    new_sc!(0x54, "SC_SYS_REQ", "SC_<00>"),
    new_sc!(0x55, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x56, "SC_BACKSLASH", "SC_HELP"),
    new_sc!(0x57, "SC_F11", "UNASSIGNED"),
    new_sc!(0x58, "SC_F12", "UNASSIGNED"),
    new_sc!(0x59, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x5A, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x5B, "UNASSIGNED", "SC_LEFT_WINDOWS"),
    new_sc!(0x5C, "UNASSIGNED", "SC_RIGHT_WINDOWS"),
    new_sc!(0x5D, "UNASSIGNED", "SC_APPLICATION"),
    new_sc!(0x5E, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x5F, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x60, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x61, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x62, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x63, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x64, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x65, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x66, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x67, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x68, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x69, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x6A, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x6B, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x6C, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x6D, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x6E, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x6F, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x70, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x71, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x72, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x73, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x74, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x75, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x76, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x77, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x78, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x79, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x7A, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x7B, "UNASSIGNED", "UNASSIGNED"),
    new_sc!(0x7C, "SC_F13", "SC_	"),
    new_sc!(0x7D, "SC_F14", "UNASSIGNED"),
    new_sc!(0x7E, "SC_F15", "UNASSIGNED"),
    new_sc!(0x7F, "SC_F16", "UNASSIGNED"),
    new_sc!(0x80, "SC_F17", "UNASSIGNED"),
    new_sc!(0x81, "SC_F18", "UNASSIGNED"),
    new_sc!(0x82, "SC_F19", "UNASSIGNED"),
    new_sc!(0x83, "SC_F20", "UNASSIGNED"),
    new_sc!(0x84, "SC_F21", "UNASSIGNED"),
    new_sc!(0x85, "SC_F22", "UNASSIGNED"),
    new_sc!(0x86, "SC_F23", "UNASSIGNED"),
    new_sc!(0x87, "SC_F24", "UNASSIGNED"),
];
