title = "Default layout (no keyboard lighting)"
icon = "image\\default.ico"

[keyboard_lighting.default]
default = ["#00000", "#000000", "#000000", "#000000"]

[sound.default]
default = "sound\\clack.wav"
