[none]
title = "No profile"
transform_layout = "default"
keyboard_locale = "en_us"

[chrome]
title = "Browser"
activation_rule = "Chrome"
transform_layout = "default_no_lighting"
keyboard_locale = "ru_ru"

[ide]
title = "IDE"
activation_rule = "rustrover64.exe"
transform_layout = "default"
keyboard_locale = "en_us"

[tc]
title = "Total commander"
activation_rule = "TOTALCMD64.EXE"
transform_layout = "ide"
