keys_logging_enabled = true
layout_autoswitch_enabled = true
toggle_layout_hot_key = "[] FN_LAUNCH_APP2↑"

[main_window]
position = [711, 182]
size = [939, 504]
selected_page = 0

[main_window.log_view.columns]
7 = 50
0 = 284
1 = 254
3 = 185
8 = 50
4 = 91
2 = 107
5 = 116
6 = 131
