keys_logging_enabled = true
layout_autoswitch_enabled = true
last_transform_layout = "default"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2↑"

[main_window]
position = [340, 237]
size = [1534, 504]
selected_page = 1

[main_window.log_view.columns]
3 = 185
2 = 107
5 = 116
7 = 50
6 = 131
4 = 91
0 = 284
1 = 254
8 = 50
