/* autogenerated by build.rs */

pub const RT_MANIFEST: usize = 24;
pub const IDI_ICON_APP: usize = 1001;
pub const IDI_ICON_GAME_LOCK_ON: usize = 1002;
pub const IDI_ICON_GAME_LOCK_OFF: usize = 1003;
pub const IDI_ICON_NUM_LOCK: usize = 1004;
